version: '3.8'

services:
  obsidian-bot:
    build: .
    container_name: obsidian-bot
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    volumes:
      - /root/obsidian-vault:/vault
      - ~/.ssh:/root/.ssh:ro