services:
  obsidian-bot:
    build: .
    container_name: obsidian-bot
    restart: always
    environment:
      - TZ=Europe/Moscow
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    volumes:
      - /root/obsidian-vault:/vault
